package org.firstinspires.ftc.teamcode.processor

import com.google.devtools.ksp.getAllSuperTypes
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * KSP processor that generates a *Group class for each target FTC hardware interface.
 *
 * For each target (e.g. DcMotorEx → MotorGroup):
 *   - Implements the interface via Kotlin 'by devices[0]' delegation (all reads free)
 *   - Overrides every void-returning method to fan out to all devices
 *   - Exposes operator fun get(index: Int) for per-device indexed access
 *   - Exposes val size: Int
 *
 * Also generates HardwareFactoryExtensions.kt with a single inline reified
 * factory.group<T>() extension covering all generated group types, with both
 * a plain-names overload and a Pair<String, Direction> overload for inline direction.
 */
class HardwareGroupProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    // Map: fully-qualified interface name -> generated class name
    private val targets = linkedMapOf(
        "com.qualcomm.robotcore.hardware.DcMotorEx" to "MotorGroup",
        "com.qualcomm.robotcore.hardware.Servo"     to "ServoGroup",
        "com.qualcomm.robotcore.hardware.CRServo"   to "CRServoGroup",
    )

    private val outputPackage = "org.firstinspires.ftc.teamcode.hardware"
    private val factoryPackage = "org.firstinspires.ftc.teamcode.di"
    private val factoryClass   = ClassName(factoryPackage, "HardwareFactory")

    // Java Object methods that appear in getAllFunctions() but must not be overridden
    private val objectMethods = setOf(
        "equals", "hashCode", "toString", "finalize",
        "getClass", "notify", "notifyAll", "wait",
    )

    private var ran = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        // KSP may call process() multiple times (deferred symbols). Only run once.
        if (ran) return emptyList()
        ran = true

        val resolved = targets.mapNotNull { (fqn, className) ->
            val decl = resolver.getClassDeclarationByName(resolver.getKSNameFromString(fqn))
            if (decl == null) {
                logger.warn("[$fqn] not found on classpath — skipping $className generation")
                null
            } else {
                Triple(fqn, className, decl)
            }
        }

        if (resolved.isEmpty()) return emptyList()

        resolved.forEach { (_, className, decl) ->
            generateGroupClass(className, decl)
        }

        generateFactoryExtensions(resolved)

        return emptyList()
    }

    // -------------------------------------------------------------------------
    // Group class generation
    // -------------------------------------------------------------------------

    private fun generateGroupClass(className: String, iface: KSClassDeclaration) {
        val ifaceTypeName = iface.toClassName()
        val listOfT = List::class.asClassName().parameterizedBy(ifaceTypeName)

        // Collect all void-returning (write) methods across the full hierarchy,
        // excluding java.lang.Object methods and non-abstract methods.
        val writeMethods = iface.getAllFunctions()
            .filter { fn ->
                fn.simpleName.asString() !in objectMethods &&
                fn.isAbstract &&
                isVoidReturn(fn)
            }
            .toList()

        val groupClass = TypeSpec.classBuilder(className)
            .addKdoc(
                "A group of [%T] devices that acts as a single [%T].\n\n" +
                "All write operations are fanned out to every device in the group.\n" +
                "All read operations are delegated to the primary device (index 0).\n" +
                "Individual devices can be accessed by index via [get].\n\n" +
                "Generated by [%L].",
                ifaceTypeName, ifaceTypeName, this::class.simpleName!!,
            )
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter("devices", listOfT)
                    .build()
            )
            .addProperty(
                PropertySpec.builder("devices", listOfT)
                    .initializer("devices")
                    .addModifiers(KModifier.PRIVATE)
                    .build()
            )
            // : InterfaceType by devices[0]
            .addSuperinterface(ifaceTypeName, CodeBlock.of("devices[0]"))
            .apply {
                writeMethods.forEach { fn -> addFunction(buildFanOutOverride(fn)) }
            }
            // operator fun get(index: Int): InterfaceType
            .addFunction(
                FunSpec.builder("get")
                    .addModifiers(KModifier.OPERATOR)
                    .addParameter("index", Int::class)
                    .returns(ifaceTypeName)
                    .addStatement("return devices[index]")
                    .build()
            )
            // val size: Int
            .addProperty(
                PropertySpec.builder("size", Int::class)
                    .getter(FunSpec.getterBuilder().addStatement("return devices.size").build())
                    .build()
            )
            .build()

        FileSpec.builder(outputPackage, className)
            .addType(groupClass)
            .build()
            .writeTo(codeGenerator, Dependencies(aggregating = false))
    }

    private fun buildFanOutOverride(fn: KSFunctionDeclaration): FunSpec {
        val params = fn.parameters.map { p ->
            ParameterSpec.builder(p.name!!.asString(), p.type.resolve().toTypeName()).build()
        }
        val args = params.joinToString(", ") { it.name }
        val call = if (args.isEmpty()) "it.${fn.simpleName.asString()}()"
                   else                "it.${fn.simpleName.asString()}($args)"

        val builder = FunSpec.builder(fn.simpleName.asString())
            .addModifiers(KModifier.OVERRIDE)
            .addParameters(params)
            .addStatement("devices.forEach·{ %L }", call)

        // Propagate @Deprecated if present on the source method
        if (fn.annotations.any { it.shortName.asString() == "Deprecated" }) {
            builder.addAnnotation(
                AnnotationSpec.builder(Deprecated::class)
                    .addMember("message = %S", "Deprecated in FTC SDK")
                    .build()
            )
            builder.addAnnotation(
                AnnotationSpec.builder(Suppress::class)
                    .addMember("%S", "DEPRECATION")
                    .build()
            )
        }

        return builder.build()
    }

    /** Returns true when the function's declared return type resolves to kotlin.Unit / void. */
    private fun isVoidReturn(fn: KSFunctionDeclaration): Boolean {
        val ret = fn.returnType?.resolve() ?: return false
        val fqn = ret.declaration.qualifiedName?.asString() ?: return false
        return fqn == "kotlin.Unit"
    }

    // -------------------------------------------------------------------------
    // HardwareFactory extension generation
    // -------------------------------------------------------------------------

    private fun generateFactoryExtensions(
        resolved: List<Triple<String, String, KSClassDeclaration>>,
    ) {
        val hardwareDeviceClass = ClassName("com.qualcomm.robotcore.hardware", "HardwareDevice")
        val dcMotorSimpleDir    = ClassName("com.qualcomm.robotcore.hardware", "DcMotorSimple", "Direction")
        val servoDir            = ClassName("com.qualcomm.robotcore.hardware", "Servo", "Direction")

        // Build function bodies as fully literal strings to avoid KotlinPoet's
        // statement-tracking treating '{' inside lambda expressions as block openers.
        val plainBody    = StringBuilder("return when (T::class) {\n")
        val directedBody = StringBuilder("return when (T::class) {\n")

        resolved.forEach { (fqn, className, _) ->
            val ifaceFqn  = fqn
            val groupFqn  = "$outputPackage.$className"
            val (getter, dirFqn) = when (fqn) {
                "com.qualcomm.robotcore.hardware.DcMotorEx" ->
                    "getMotor"   to "com.qualcomm.robotcore.hardware.DcMotorSimple.Direction"
                "com.qualcomm.robotcore.hardware.Servo"     ->
                    "getServo"   to "com.qualcomm.robotcore.hardware.Servo.Direction"
                "com.qualcomm.robotcore.hardware.CRServo"   ->
                    "getCRServo" to "com.qualcomm.robotcore.hardware.DcMotorSimple.Direction"
                else -> return@forEach
            }
            plainBody.append("  $ifaceFqn::class -> $groupFqn(names.map { $getter(it) })\n")
            directedBody.append(
                "  $ifaceFqn::class -> $groupFqn(namedDevices.map { (n, d) -> $getter(n).also { it.direction = d as $dirFqn } })\n"
            )
        }
        val elseClause = "  else -> throw IllegalArgumentException(\"No group defined for \${T::class.simpleName}\")\n"
        plainBody.append(elseClause).append("} as T\n")
        directedBody.append(elseClause).append("} as T\n")

        val tVar = com.squareup.kotlinpoet.TypeVariableName("T", hardwareDeviceClass)
            .copy(reified = true)
        val suppressAnnotation = AnnotationSpec.builder(Suppress::class)
            .addMember("%S", "UNCHECKED_CAST")
            .build()

        // Plain overload: group<T>(vararg names: String)
        val plainFun = FunSpec.builder("group")
            .receiver(factoryClass)
            .addAnnotation(suppressAnnotation)
            .addTypeVariable(tVar)
            .addModifiers(KModifier.INLINE)
            .addParameter("names", String::class, KModifier.VARARG)
            .returns(com.squareup.kotlinpoet.TypeVariableName("T"))
            .addCode(plainBody.toString())
            .build()

        // Directed overload: group<T>(vararg namedDevices: Pair<String, Any>)
        val pairType = Pair::class.asClassName().parameterizedBy(
            String::class.asClassName(),
            Any::class.asClassName(),
        )
        val directedFun = FunSpec.builder("group")
            .receiver(factoryClass)
            .addAnnotation(suppressAnnotation)
            .addTypeVariable(tVar)
            .addModifiers(KModifier.INLINE)
            .addParameter("namedDevices", pairType, KModifier.VARARG)
            .returns(com.squareup.kotlinpoet.TypeVariableName("T"))
            .addCode(directedBody.toString())
            .build()

        FileSpec.builder(factoryPackage, "HardwareFactoryExtensions")
            .addFunction(plainFun)
            .addFunction(directedFun)
            .build()
            .writeTo(codeGenerator, Dependencies(aggregating = false))
    }
}
