package org.firstinspires.ftc.teamcode.di

import com.qualcomm.robotcore.hardware.HardwareMap
import me.tatarka.inject.annotations.Provides
import org.firstinspires.ftc.teamcode.subsystems.IntakeSubsystem
import org.firstinspires.ftc.teamcode.subsystems.LimelightSubsystem
import org.firstinspires.ftc.teamcode.subsystems.MecanumSubsystem
import org.firstinspires.ftc.teamcode.subsystems.OuttakeSubsystem
import org.firstinspires.ftc.teamcode.subsystems.SpindexerSubsystem
import org.firstinspires.ftc.teamcode.subsystems.TransferSubsystem
import software.amazon.lastmile.kotlin.inject.anvil.MergeComponent
import software.amazon.lastmile.kotlin.inject.anvil.SingleIn

/**
 * Main Dependency Injection container for the robot.
 *
 * Usage in OpMode:
 * ```
 * val container = HardwareContainer::class.create()
 * ```
 *
 * The @MergeComponent annotation automatically includes all classes
 * annotated with @ContributesBinding or @ContributesTo for the TeleOpScope.
 *
 * Note: The `create()` extension function is generated by KSP.
 */
@MergeComponent(HardwareScope::class)
@SingleIn(HardwareScope::class)
abstract class HardwareContainer(@get:Provides val hardwareMap: HardwareMap) {
    abstract val mecanum: MecanumSubsystem
    abstract val intake: IntakeSubsystem
    abstract val outtake: OuttakeSubsystem
    abstract val limelight: LimelightSubsystem
    abstract val spindexer: SpindexerSubsystem
    abstract val transfer: TransferSubsystem

    companion object Companion
}