package org.firstinspires.ftc.teamcode.di

import com.pedropathing.follower.Follower
import com.qualcomm.robotcore.hardware.HardwareMap
import me.tatarka.inject.annotations.Provides
import org.firstinspires.ftc.teamcode.pedroPathing.Constants
import org.firstinspires.ftc.teamcode.subsystems.interfaces.*
import software.amazon.lastmile.kotlin.inject.anvil.MergeComponent
import software.amazon.lastmile.kotlin.inject.anvil.SingleIn

/**
 * Main Dependency Injection container for the robot.
 *
 * Usage in OpMode:
 * ```
 * val container = HardwareContainer::class.create(hardwareMap)
 * ```
 *
 * The @MergeComponent annotation automatically includes all classes
 * annotated with @Inject for the HardwareScope.
 *
 * Note: The `create()` extension function is generated by KSP.
 */
@MergeComponent(HardwareScope::class)
@SingleIn(HardwareScope::class)
abstract class HardwareContainer(@get:Provides val hardwareMap: HardwareMap) {
    // Expose interfaces, not concrete classes
    abstract val drive: DriveSubsystem
    abstract val intake: IntakeSubsystem
    abstract val outtake: OuttakeSubsystem
    abstract val limelight: LimelightSubsystem
    abstract val spindexer: SpindexerSubsystem
    abstract val transfer: TransferSubsystem
    
    // Pedro Pathing Follower for odometry
    abstract val follower: Follower
    
    /**
     * Provider for Pedro Pathing Follower.
     * Creates and configures the Follower instance for odometry.
     */
    @Provides
    @SingleIn(HardwareScope::class)
    fun provideFollower(hardwareMap: HardwareMap): Follower {
        return Constants.createFollower(hardwareMap)
    }

    companion object Companion
}