package org.firstinspires.ftc.teamcode.di

import org.firstinspires.ftc.teamcode.robot.Robot
import org.firstinspires.ftc.teamcode.subsystems.IntakeSubsystem
import org.firstinspires.ftc.teamcode.subsystems.LimelightSubsystem
import org.firstinspires.ftc.teamcode.subsystems.MecanumSubsystem
import org.firstinspires.ftc.teamcode.subsystems.OuttakeSubsystem
import org.firstinspires.ftc.teamcode.subsystems.SpindexerSubsystem
import org.firstinspires.ftc.teamcode.subsystems.Subsystem
import org.firstinspires.ftc.teamcode.subsystems.TransferSubsystem
import software.amazon.lastmile.kotlin.inject.anvil.MergeComponent
import software.amazon.lastmile.kotlin.inject.anvil.SingleIn

/**
 * Main DI component for the robot.
 *
 * Usage in OpMode:
 * ```
 * val component = RobotComponent::class.create()
 * component.robot.init(hardwareMap)
 * ```
 *
 * The @MergeComponent annotation automatically includes all classes
 * annotated with @ContributesBinding or @ContributesTo for the RobotScope.
 *
 * Note: The `create()` extension function is generated by KSP.
 */
@MergeComponent(RobotScope::class)
@SingleIn(RobotScope::class)
abstract class RobotComponent {
    abstract val robot: Robot

    // Expose the set of all subsystems (contributed via multibinding)
    abstract val subsystems: Set<Subsystem>

    // Direct access to individual subsystems
    abstract val mecanum: MecanumSubsystem
    abstract val intake: IntakeSubsystem
    abstract val outtake: OuttakeSubsystem
    abstract val limelight: LimelightSubsystem
    abstract val spindexer: SpindexerSubsystem
    abstract val transfer: TransferSubsystem

    companion object
}
